/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_management;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CourseSelection extends javax.swing.JFrame {
String courses1 ;
String courses2 ;
String courses3 ;
String courses4 ;
String courses5 ;
String username;
int p=0;
    /**
     * Creates new form CourseSelection
     */
    public CourseSelection(String name) {
        initComponents();
        username = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        course1 = new javax.swing.JCheckBox();
        course2 = new javax.swing.JCheckBox();
        course3 = new javax.swing.JCheckBox();
        course4 = new javax.swing.JCheckBox();
        course5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        course1.setBackground(new java.awt.Color(204, 255, 204));
        course1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        course1.setText("IDBM432C");
        course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1ActionPerformed(evt);
            }
        });
        getContentPane().add(course1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 109, 141, 43));

        course2.setBackground(new java.awt.Color(204, 255, 204));
        course2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        course2.setText("IDAA432C");
        course2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course2ActionPerformed(evt);
            }
        });
        getContentPane().add(course2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 182, 141, 43));

        course3.setBackground(new java.awt.Color(204, 255, 204));
        course3.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        course3.setText("SMAT430C");
        course3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course3ActionPerformed(evt);
            }
        });
        getContentPane().add(course3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 259, 141, 43));

        course4.setBackground(new java.awt.Color(204, 255, 204));
        course4.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        course4.setText("EPOC432C");
        course4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course4ActionPerformed(evt);
            }
        });
        getContentPane().add(course4, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 150, -1, 33));

        course5.setBackground(new java.awt.Color(204, 255, 204));
        course5.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        course5.setText("IPPL430C");
        getContentPane().add(course5, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 221, 125, 42));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Courses");
        jLabel1.setAlignmentX(5.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 26, 159, 50));

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 392, 139, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\gurmeet\\Desktop\\dbms7.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void course1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_course1ActionPerformed

    private void course4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_course4ActionPerformed

    private void course2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course2ActionPerformed
          
    }//GEN-LAST:event_course2ActionPerformed

    private void course3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course3ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_course3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(course1.isSelected())
        {
            p++;
            courses1 = "IDBM432C";
            conn c=new conn();
            int rows;
            String q="Insert Into Student_work(id,Course_Code) values('"+username+"','"+courses1+"')";
            try{
                rows=c.s.executeUpdate(q);
            }
            catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
        }
        if(course2.isSelected())
        {p++;
            courses2 = "IDAA432C";
        conn c=new conn();
            int rows;
            String q="Insert Into Student_work(id,Course_Code) values('"+username+"','"+courses2+"')";
            try{
                rows=c.s.executeUpdate(q);
            }
            catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
            }
         if(course3.isSelected())
         {p++;
             courses3 = "SMAT430C";
              conn c=new conn();
            int rows;
            String q="Insert Into Student_work(id,Course_Code) values('"+username+"','"+courses3+"')";
            try{
                rows=c.s.executeUpdate(q);
            }
            catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
         }
         if(course4.isSelected())
         {p++;
             courses4 = "EPOC432C";
              conn c=new conn();
            int rows;
            String q="Insert Into Student_work(id,Course_Code) values('"+username+"','"+courses4+"')";
            try{
                rows=c.s.executeUpdate(q);
            }
            catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
         }
         if(course5.isSelected())
         {p++;
             courses5 = "IPPL430C";
              conn c=new conn();
            int rows;
            String q="Insert Into Student_work(id,Course_Code) values('"+username+"','"+courses5+"')";
            try{
                rows=c.s.executeUpdate(q);
            }
            catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
         }
         if(p>0)
         {
              JOptionPane.showMessageDialog(null,"Student Signed up","Sign up Successful",2);
                dispose();
        Admin admin = new Admin();
        admin.setVisible(true);
         }
         if(p==0)
         { JOptionPane.showMessageDialog(null, "Enter a course","Sign up Failed",2);
         }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CourseSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox course1;
    private javax.swing.JCheckBox course2;
    private javax.swing.JCheckBox course3;
    private javax.swing.JCheckBox course4;
    private javax.swing.JCheckBox course5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
