/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package course_management;

import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class CourseIns extends javax.swing.JFrame {
     String code;
     
     JFileChooser chooser;
    /** Creates new form CourseIns */
    public CourseIns(String s) {
        this.code=s;
        initComponents();
        fill();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cclabel = new javax.swing.JLabel();
        cnlabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HLabel.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        HLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(HLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 707, 70));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("Course Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 118, 124, 46));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel2.setText("Course Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 228, 124, 44));

        cclabel.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        cclabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cclabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 118, 220, 46));

        cnlabel.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        cnlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 228, 343, 44));

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton1.setText("Upload Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 334, -1, 55));

        jButton4.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 340, 113, 43));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\gurmeet\\Desktop\\dbms5.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-17, 0, 760, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.setFileFilter(new FileNameExtensionFilter("PDF files","pdf"));
        int result = chooser.showSaveDialog(this);
       if (result == JFileChooser.APPROVE_OPTION) {
           //JOptionPane.showMessageDialog(this, chooser.getSelectedFile());
           
           File filename = chooser.getSelectedFile();
  
           String filepath= filename.getAbsolutePath();
           conn c=new conn();
        //conn c=new conn();
       int rows;
          String q="Update Instructor set Assignment = '"+filepath+"' where id='"+code+"' ";
          try{
              rows=c.s.executeUpdate(q);
          }
          catch(SQLException ex){
                   Logger.getLogger(CourseIns.class.getName()).log(Level.SEVERE, null, ex);
                   }
          JOptionPane.showMessageDialog(this,"Assignment Uploaded Successfully!");
       }
       else{
           JOptionPane.showMessageDialog(this, "No file Selected");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        Instructor s=new Instructor(code);
        s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void fill(){
         
        conn c=new conn();
        ResultSet rs;
        String q = "select * from Instructor where id ='"+code+"'";
        conn c1=new conn();
        ResultSet rs1;
        String r = null;
        try{
            rs=c.s.executeQuery(q);
            if(rs.next()){
             HLabel.setText("Hi "+rs.getString("T_name")+", your course details are: "); 
             cclabel.setText(rs.getString("Course_Code"));
             //r=rs.getString("Course_Code");
        }
        }
        catch(SQLException ex){
                   Logger.getLogger(CourseIns.class.getName()).log(Level.SEVERE, null, ex);
                   }
         
             String q1 = "select * from Course where Instructor_Code ='"+code+"'";
             try{
                 rs1=c1.s.executeQuery(q1);
                 if(rs1.next()){
                     cnlabel.setText(rs1.getString("Course_Name"));
                 }
             }
             catch(SQLException ex){
                   Logger.getLogger(CourseIns.class.getName()).log(Level.SEVERE, null, ex);
                   }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CourseIns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HLabel;
    private javax.swing.JLabel cclabel;
    private javax.swing.JLabel cnlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
