/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_management;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
/**

 * @author DELL
 */
public class Student extends javax.swing.JFrame {
Connection myconn=null;
     Statement  myStat=null;
     ResultSet myRs=null;
     String choose;
/*JComboBox jComboBox2 = new JComboBox();
                t1.add(jComboBox2);
                jComboBox2.addItem("asdf");*/
   public String name;
    public Student(String id) {
        initComponents();
        this.name=id;
        WLabel.setText("Welcome "+name+" ");
        fill();
        fillcombo();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WLabel = new javax.swing.JLabel();
        CourseList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WLabel.setFont(new java.awt.Font("Gill Sans MT", 1, 34)); // NOI18N
        WLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(WLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 586, 110));

        CourseList.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        CourseList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CourseList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseListActionPerformed(evt);
            }
        });
        getContentPane().add(CourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 274, 186, 53));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("My Courses List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 274, 185, 53));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel2.setText("Student  Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 162, 185, 41));

        txt_name.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 162, 277, 36));

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 273, -1, 54));

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 22, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\gurmeet\\Desktop\\dbms7.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void fill(){
    conn c1=new conn();
        conn c=new conn();
        ResultSet rs;
        String n;
        String q="Select * from Student where id='"+name+"' ";
        try{
            rs=c.s.executeQuery(q);
            if(rs.next()){
                n=rs.getString("S_name");
                txt_name.setText(n);
            }
        }
        catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
}
    private void CourseListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseListActionPerformed
        // TODO add your handling code here:
        choose=(String)CourseList.getSelectedItem();
    }//GEN-LAST:event_CourseListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          dispose();  
        Course myCourse= new Course(name,choose);
       
        myCourse.clabel.setText("Hi "+name+", "+ choose+" Course Details are: ");
          myCourse.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Welcome w = new Welcome();
        w.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Student t1 = new Student();
   // Object cmboitem = jComboBox2.getSelectedItem();
   // t1.setVisible(true);
                  
            }
        });
    }
   public void fillcombo(){
       
         PreparedStatement ps;
        conn c1=new conn();
        conn c=new conn();
        ResultSet rs;

       try{
                  System.out.println(name);
           String sql="select * from Student_work where id = '"+name+"'";
            rs = c1.s.executeQuery(sql);
      
            CourseList.removeAllItems();
                  
           while(rs.next()){
               String course=rs.getString("Course_Code");
             
               CourseList.addItem(course);
               
           }
       }
           catch(SQLException ex){
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                   }
       }
       
       
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CourseList;
    public javax.swing.JLabel WLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txt_name;
    // End of variables declaration//GEN-END:variables
}
