/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_management;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class StudentsEnrolled extends javax.swing.JFrame {
      String tcode;
      

    
     public StudentsEnrolled(String tcode) {
         this.tcode=tcode;
        
        initComponents();
        fill();
        show_std();
    }
    /**
     * Creates new form StudentsEnrolled
     */
    public ArrayList<Student_work> stdList(){
   ArrayList<Student_work> Std_work = new ArrayList<Student_work>();
   conn c=new conn();
    ResultSet rs; 
    String ccode=null;
    String q="Select * from Instructor where id='"+tcode+"' ";
    try{
        rs=c.s.executeQuery(q);
        if(rs.next()){
           ccode=rs.getString("Course_Code");
        }
    }
    catch(SQLException ex){
                   Logger.getLogger(StudentsEnrolled.class.getName()).log(Level.SEVERE, null, ex);
      }
    conn c1=new conn();
    ResultSet rs1;
    String q1="Select * from Student_work where Course_Code='"+ccode+"'";
    try{
        Student_work std;
        rs1=c1.s.executeQuery(q1);
        while(rs1.next()){
           std=new Student_work(rs1.getString("id"),rs1.getString("grade"),rs1.getInt("marks"),rs1.getInt("Att_percent"));
           Std_work.add(std);
        } 
    }
    catch(SQLException ex){
                   Logger.getLogger(StudentsEnrolled.class.getName()).log(Level.SEVERE, null, ex);
                   }
    return Std_work;
}
   public void fill(){
    conn c=new conn();
    ResultSet rs; 
    String q="Select * from Instructor where id='"+tcode+"' ";
    try{
        rs=c.s.executeQuery(q);
        if(rs.next()){
            welabel.setText("Hi "+ rs.getString("T_name")+" ,Your Enrolled Students are:");
        }
    }
    catch(SQLException ex){
                   Logger.getLogger(StudentsEnrolled.class.getName()).log(Level.SEVERE, null, ex);
                   }
   }
   public void show_std(){
       ArrayList<Student_work> list= stdList();
       DefaultTableModel model=(DefaultTableModel)showStudents.getModel();
       Object[] row=new Object[4];
       for(int i=0;i<list.size();i++){
          row[0]=list.get(i).getsid();
          row[1]=list.get(i).getatt();
          row[2]=list.get(i).getgrade();
          row[3]=list.get(i).getmarks();
          model.addRow(row);
       }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        showStudents = new javax.swing.JTable();
        welabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        updtext = new javax.swing.JTextField();
        updmarks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        updatt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        upgrade = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showStudents.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        showStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment Number", "Attendance", "Grade", "Marks"
            }
        ));
        jScrollPane1.setViewportView(showStudents);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 490, 167));

        welabel.setFont(new java.awt.Font("Gill Sans MT", 1, 22)); // NOI18N
        welabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(welabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 763, 90));

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton1.setText("Update Marks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 370, 230, 40));

        updtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtextActionPerformed(evt);
            }
        });
        getContentPane().add(updtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 180, 30));

        updmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updmarksActionPerformed(evt);
            }
        });
        getContentPane().add(updmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 100, 30));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("Enrollment Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 36));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Marks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 100, 20));

        jButton4.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 10, 113, 43));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Attendance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 120, 30));

        updatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updattActionPerformed(evt);
            }
        });
        getContentPane().add(updatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 120, 30));

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton2.setText("Update Attendance");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 240, 50));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Grade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 70, 20));

        upgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgradeActionPerformed(evt);
            }
        });
        getContentPane().add(upgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 90, 30));

        jButton3.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton3.setText("Update Grade");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\gurmeet\\Desktop\\dbms7.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conn c=new conn();
    ResultSet rs; 
    String ccode=null;
    String q="Select * from Instructor where id='"+tcode+"' ";
    try{
        rs=c.s.executeQuery(q);
        if(rs.next()){
           ccode=rs.getString("Course_Code");
        }
    }
    catch (SQLException ex) {
            Logger.getLogger(StudentsEnrolled.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
            {PreparedStatement ps=null;
        conn c1=new conn();
       
        ResultSet rs1;        
        String uname = updtext.getText();
        String umarks=updmarks.getText();
        Integer markn=Integer.parseInt(umarks);
        String query = "update Student_work set marks ="+markn+" where id = '"+uname+"' and Course_Code= '"+ccode+"'";
           
            int row1 = c1.s.executeUpdate(query);
                    JOptionPane.showMessageDialog(this,"Marks Updated Successfully!");
         
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginInstructor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updtextActionPerformed

    private void updmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updmarksActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        Instructor s=new Instructor(tcode);
        s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void updattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updattActionPerformed
      
    }//GEN-LAST:event_updattActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
         conn c=new conn();
    ResultSet rs; 
    String ccode=null;
    String q="Select * from Instructor where id='"+tcode+"' ";
    try{
        rs=c.s.executeQuery(q);
        if(rs.next()){
           ccode=rs.getString("Course_Code");
        }
    }
    catch (SQLException ex) {
            Logger.getLogger(StudentsEnrolled.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
            {PreparedStatement ps=null;
        conn c1=new conn();
       
        ResultSet rs1;        
        String uname = updtext.getText();
        String uatt=updatt.getText();
        Integer markn=Integer.parseInt(uatt);
        String query = "update Student_work set Att_percent ="+markn+" where id = '"+uname+"' and Course_Code= '"+ccode+"'";
           
            int row1 = c1.s.executeUpdate(query);
                    JOptionPane.showMessageDialog(this,"Attendance Updated Successfully!");
         
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginInstructor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        conn c=new conn();
    ResultSet rs; 
    String ccode=null;
    String q="Select * from Instructor where id='"+tcode+"' ";
    try{
        rs=c.s.executeQuery(q);
        if(rs.next()){
           ccode=rs.getString("Course_Code");
        }
    }
    catch (SQLException ex) {
            Logger.getLogger(StudentsEnrolled.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
            {PreparedStatement ps=null;
        conn c1=new conn();
       
        ResultSet rs1;        
        String uname = updtext.getText();
        String markn=upgrade.getText();
        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter ID");
        }
        else if(markn.equals("")) 
        {
            JOptionPane.showMessageDialog(this,"Please Enter Grade");
        }
        String query = "update Student_work set Grade = '"+markn+"' where id = '"+uname+"' and Course_Code= '"+ccode+"'";
           
            int row1 = c1.s.executeUpdate(query);
                    JOptionPane.showMessageDialog(this,"Grade Updated Successfully!");
         
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginInstructor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void upgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upgradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsEnrolled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new StudentsEnrolled().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable showStudents;
    private javax.swing.JTextField updatt;
    private javax.swing.JTextField updmarks;
    private javax.swing.JTextField updtext;
    private javax.swing.JTextField upgrade;
    private javax.swing.JLabel welabel;
    // End of variables declaration//GEN-END:variables
}
