/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_management;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author gurmeet
 */
public class tamarks extends javax.swing.JFrame {
Connection myconn=null;
     Statement  myStat=null;
     ResultSet myRs=null;
     String user;
    /**
     * Creates new form 
     */
    public tamarks(String username) {
        initComponents();
        user = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        showmarks = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updtext = new javax.swing.JTextField();
        updmarks = new javax.swing.JTextField();
        upd = new javax.swing.JButton();
        update = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course_management/Ins.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 216));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("MARKS DISPLAY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 21, 212, 48));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 236, 104, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 239, 36, 37));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 236, 91, -1));

        showmarks.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(showmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 307, 285, 93));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("        UPDATE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 141, 215, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 236, 87, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("NEW MARKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 120, 35));
        getContentPane().add(updtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 236, 138, 40));
        getContentPane().add(updmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 307, 138, 35));

        upd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        upd.setText("UPDATE");
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });
        getContentPane().add(upd, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 360, 138, 31));

        update.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 417, 245, 48));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 428, 136, 52));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\gurmeet\\Desktop\\dbms5.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 750, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         PreparedStatement ps;
        conn c1=new conn();
        conn c=new conn();
        ResultSet rs;
        ResultSet rs1;
        String uname = txt_id.getText();
        
        String query = "SELECT marks FROM Student_work where id = '"+uname+"'";
        try {
           
            rs = c1.s.executeQuery(query);
            if(rs.next())
            {
                    showmarks.setText("The Marks are "+rs.getString("marks"));
                    
            }
            else{
                    JOptionPane.showMessageDialog(null, "Username incorrect", "Login Failed", 2);
                    txt_id.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginInstructor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
        // TODO add your handling code here:
        try
            {PreparedStatement ps=null;
        conn c1=new conn();
        conn c=new conn();
        ResultSet rs;
        ResultSet rs1;        
        String uname = updtext.getText();
        String umarks=updmarks.getText();
        Integer markn=Integer.parseInt(umarks);
        String cid=null;
        String q1="select course from tadata where name='"+user+"'";
        rs = c1.s.executeQuery(q1);
         if(rs.next())
         {
             cid=rs.getString("course");
         }
         else{
                JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", 2);
        }
        String query = "update Student_work set marks ="+markn+" where id = '"+uname+"'";
        int row1 = c1.s.executeUpdate(query);
            if(row1>0)
            {
                    update.setText("Updated");
                    
            }
            else{
                    JOptionPane.showMessageDialog(null, "Username incorrect", "Login Failed", 2);
                    update.setText("");
                }
        } catch (SQLException ex) {
            Logger.getLogger(LoginInstructor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TA tan=new TA(user);
        tan.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tamarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tamarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tamarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tamarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tamarks("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel showmarks;
    private javax.swing.JTextField txt_id;
    private javax.swing.JButton upd;
    private javax.swing.JLabel update;
    private javax.swing.JTextField updmarks;
    private javax.swing.JTextField updtext;
    // End of variables declaration//GEN-END:variables
}
